<a href="https://colab.research.google.com/github/abir-mahamud/nlp/blob/main/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:

### Vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4361, 2967, 2275, 112], [4361, 2967, 2275, 7694], [4361, 9993, 2275, 8835], [5794, 4371, 6676, 3727, 593], [5794, 4371, 6676, 3727, 5062], [6598, 4361, 250, 2275, 8878], [5376, 573, 3275, 3727]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4361 2967 2275  112]
 [   0    0    0    0 4361 2967 2275 7694]
 [   0    0    0    0 4361 9993 2275 8835]
 [   0    0    0 5794 4371 6676 3727  593]
 [   0    0    0 5794 4371 6676 3727 5062]
 [   0    0    0 6598 4361  250 2275 8878]
 [   0    0    0    0 5376  573 3275 3727]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:

print(model.predict(embedded_docs))

[[[-4.36373018e-02  2.21892484e-02  3.97532247e-02  1.14545710e-02
   -4.54238541e-02  1.09376907e-02  3.66347320e-02  4.20382880e-02
    3.02621759e-02  4.26631905e-02]
  [-4.36373018e-02  2.21892484e-02  3.97532247e-02  1.14545710e-02
   -4.54238541e-02  1.09376907e-02  3.66347320e-02  4.20382880e-02
    3.02621759e-02  4.26631905e-02]
  [-4.36373018e-02  2.21892484e-02  3.97532247e-02  1.14545710e-02
   -4.54238541e-02  1.09376907e-02  3.66347320e-02  4.20382880e-02
    3.02621759e-02  4.26631905e-02]
  [-4.36373018e-02  2.21892484e-02  3.97532247e-02  1.14545710e-02
   -4.54238541e-02  1.09376907e-02  3.66347320e-02  4.20382880e-02
    3.02621759e-02  4.26631905e-02]
  [ 1.22884028e-02  3.88053320e-02 -2.07348950e-02  1.26908086e-02
   -4.58455347e-02  4.16887291e-02 -3.84061337e-02  2.07794569e-02
    2.12536938e-02  2.38750316e-02]
  [-4.24143560e-02 -4.48185913e-02  2.09852345e-02  2.85545848e-02
    3.26247104e-02  3.08811702e-02 -1.19157322e-02  2.65511125e-03
    1.39025785e-

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 4361, 2967, 2275,  112], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

[[-4.36373018e-02  2.21892484e-02  3.97532247e-02  1.14545710e-02
  -4.54238541e-02  1.09376907e-02  3.66347320e-02  4.20382880e-02
   3.02621759e-02  4.26631905e-02]
 [-4.36373018e-02  2.21892484e-02  3.97532247e-02  1.14545710e-02
  -4.54238541e-02  1.09376907e-02  3.66347320e-02  4.20382880e-02
   3.02621759e-02  4.26631905e-02]
 [-4.36373018e-02  2.21892484e-02  3.97532247e-02  1.14545710e-02
  -4.54238541e-02  1.09376907e-02  3.66347320e-02  4.20382880e-02
   3.02621759e-02  4.26631905e-02]
 [-4.36373018e-02  2.21892484e-02  3.97532247e-02  1.14545710e-02
  -4.54238541e-02  1.09376907e-02  3.66347320e-02  4.20382880e-02
   3.02621759e-02  4.26631905e-02]
 [ 1.22884028e-02  3.88053320e-02 -2.07348950e-02  1.26908086e-02
  -4.58455347e-02  4.16887291e-02 -3.84061337e-02  2.07794569e-02
   2.12536938e-02  2.38750316e-02]
 [-4.24143560e-02 -4.48185913e-02  2.09852345e-02  2.85545848e-02
   3.26247104e-02  3.08811702e-02 -1.19157322e-02  2.65511125e-03
   1.39025785e-02 -2.21894626e-02